// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides', }],
};

module.exports = sidebars;