// guides_sidebars.js
module.exports = {
  guidesSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },
    {
      type: 'doc',
      id: 'get-started',
      label: 'Get started',
    },
    {
      type: 'category',
      label: 'Conduktor in production',
      link: { type: 'doc', id: 'conduktor-in-production/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'conduktor-in-production',
        },
      ],
    },

    {
      type: 'category',
      label: 'Manage Kafka',
      items: [
        {
          type: 'autogenerated',
          dirName: 'manage-kafka',
        },
      ],
    },  
    {
      type: 'category',
      label: 'Monitor clusters and apps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'monitor-clusters-apps',
        },
      ],
    },  

    // Non-clickable section after use cases - Concepts
    {
      type: 'html',
      value: '<span class="sidebar-heading">Concepts</span>',
      className: 'sidebar-section-heading',
    },
    {
      type: 'category',
      label: 'Conduktor concepts',
      link: { type: 'doc', id: 'conduktor-concepts/index' },
      // Manually list all concept docs except the index file
      items: [
        'conduktor-concepts/alias-topics',
        'conduktor-concepts/chargeback',
        'conduktor-concepts/indexing',
      ],
    },

    // Non-clickable section after use cases - Use cases
    {
      type: 'html',
      value: '<span class="sidebar-heading">Use cases</span>',
      className: 'sidebar-section-heading',
    },
    {
      type: 'category',
      label: 'Apply Chargeback',
      link: { type: 'doc', id: 'use-cases/chargeback/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Use Self-service',
      link: { type: 'doc', id: 'use-cases/self-service/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Share data',
      link: { type: 'doc', id: 'use-cases/third-party-data/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Encrypt Kafka data',
      link: { type: 'doc', id: 'use-cases/encrypt-kafka/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Perform chaos testing',
      link: { type: 'doc', id: 'use-cases/chaos-testing/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Control traffic',
      link: { type: 'doc', id: 'use-cases/control-traffic/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Manage large messages',
      link: { type: 'doc', id: 'use-cases/manage-large-messages/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Define Rules and Policies',
      link: { type: 'doc', id: 'use-cases/rules-policies/index' },
      items: [],
    },

    // Non-clickable section after use cases - Tutorials
    {
      type: 'html',
      value: '<span class="sidebar-heading">Tutorials</span>',
      className: 'sidebar-section-heading',
    },
    {
      type: 'category',
      label: 'Conduktor tutorials',
      link: { type: 'doc', id: 'tutorials/index' },
      items: [],
    }, 

    // Non-clickable section after use cases - Reference
    {
      type: 'html',
      value: '<span class="sidebar-heading">Reference</span>',
      className: 'sidebar-section-heading',
    },
    {
      type: 'category',
      label: 'Conduktor reference',
      link: { type: 'doc', id: 'reference/index' },
      items: ['reference/api-reference', 'reference/cli-reference', 'reference/console-reference', 'reference/kafka-reference', 'reference/metric-reference', 'reference/self-service-reference', 'reference/terraform-reference'],
    },  

    // Non-clickable section after use cases - Support
    {
      type: 'html',
      value: '<span class="sidebar-heading">Support</span>',
      className: 'sidebar-section-heading',
    },
    {
      type: 'category',
      label: 'Support options',
      link: { type: 'doc', id: 'support/index' },
      items: ['support/upgrade', 'support/version-matrix' ],
    },  
  ],
};